import type { Metadata } from "next";
import "./globals.css";
import { Marvel } from "next/font/google";
import Navbar from "./components/Navbar";

const marvel = Marvel({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${marvel.className} bg-gray-900 text-white min-h-screen`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
